@baseUrl = http://localhost:5000
##################################################


################################################## dbtest
GET {{baseUrl}}/dbtest/Categories
#####

################################################## employees
GET {{baseUrl}}/employees
#####
