/*
 * NorthwindMinApiMitWPF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// OrderDto
    /// </summary>
    [DataContract(Name = "OrderDto")]
    public partial class OrderDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderDto" /> class.
        /// </summary>
        /// <param name="orderId">orderId.</param>
        /// <param name="orderDate">orderDate.</param>
        /// <param name="isShipped">isShipped.</param>
        /// <param name="nrItems">nrItems.</param>
        public OrderDto(int orderId = default, string orderDate = default, bool isShipped = default, int nrItems = default)
        {
            this.OrderId = orderId;
            this.OrderDate = orderDate;
            this.IsShipped = isShipped;
            this.NrItems = nrItems;
        }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [DataMember(Name = "orderId", EmitDefaultValue = false)]
        public int OrderId { get; set; }

        /// <summary>
        /// Gets or Sets OrderDate
        /// </summary>
        [DataMember(Name = "orderDate", EmitDefaultValue = true)]
        public string OrderDate { get; set; }

        /// <summary>
        /// Gets or Sets IsShipped
        /// </summary>
        [DataMember(Name = "isShipped", EmitDefaultValue = true)]
        public bool IsShipped { get; set; }

        /// <summary>
        /// Gets or Sets NrItems
        /// </summary>
        [DataMember(Name = "nrItems", EmitDefaultValue = false)]
        public int NrItems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderDto {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  OrderDate: ").Append(OrderDate).Append("\n");
            sb.Append("  IsShipped: ").Append(IsShipped).Append("\n");
            sb.Append("  NrItems: ").Append(NrItems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
