/*
 * NorthwindMinApiMitWPF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerDto
        //private CustomerDto instance;

        public CustomerDtoTests()
        {
            // TODO uncomment below to create an instance of CustomerDto
            //instance = new CustomerDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerDto
        /// </summary>
        [Fact]
        public void CustomerDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerDto
            //Assert.IsType<CustomerDto>(instance);
        }

        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }

        /// <summary>
        /// Test the property 'ContactName'
        /// </summary>
        [Fact]
        public void ContactNameTest()
        {
            // TODO unit test for the property 'ContactName'
        }
    }
}
