/*
 * NorthwindMinApiMitWPF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDetailDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDetailDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDetailDto
        //private OrderDetailDto instance;

        public OrderDetailDtoTests()
        {
            // TODO uncomment below to create an instance of OrderDetailDto
            //instance = new OrderDetailDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDetailDto
        /// </summary>
        [Fact]
        public void OrderDetailDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDetailDto
            //Assert.IsType<OrderDetailDto>(instance);
        }

        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }

        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [Fact]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }

        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Fact]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
    }
}
