/*
 * NorthwindMinApiMitWPF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDto
        //private OrderDto instance;

        public OrderDtoTests()
        {
            // TODO uncomment below to create an instance of OrderDto
            //instance = new OrderDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDto
        /// </summary>
        [Fact]
        public void OrderDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDto
            //Assert.IsType<OrderDto>(instance);
        }

        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }

        /// <summary>
        /// Test the property 'OrderDate'
        /// </summary>
        [Fact]
        public void OrderDateTest()
        {
            // TODO unit test for the property 'OrderDate'
        }

        /// <summary>
        /// Test the property 'IsShipped'
        /// </summary>
        [Fact]
        public void IsShippedTest()
        {
            // TODO unit test for the property 'IsShipped'
        }

        /// <summary>
        /// Test the property 'NrItems'
        /// </summary>
        [Fact]
        public void NrItemsTest()
        {
            // TODO unit test for the property 'NrItems'
        }
    }
}
