/*
 * NorthwindMinApiMitWPF
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing MinApiBackendApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MinApiBackendApiTests : IDisposable
    {
        private MinApiBackendApi instance;

        public MinApiBackendApiTests()
        {
            instance = new MinApiBackendApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MinApiBackendApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MinApiBackendApi
            //Assert.IsType<MinApiBackendApi>(instance);
        }

        /// <summary>
        /// Test CustomersGet
        /// </summary>
        [Fact]
        public void CustomersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.CustomersGet();
            //Assert.IsType<List<CustomerDto>>(response);
        }

        /// <summary>
        /// Test DbtestCategoriesGet
        /// </summary>
        [Fact]
        public void DbtestCategoriesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.DbtestCategoriesGet();
            //Assert.IsType<OkMessage>(response);
        }

        /// <summary>
        /// Test EmployeesGet
        /// </summary>
        [Fact]
        public void EmployeesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.EmployeesGet();
            //Assert.IsType<List<EmployeeDto>>(response);
        }

        /// <summary>
        /// Test OrderdetailsGet
        /// </summary>
        [Fact]
        public void OrderdetailsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int orderId = null;
            //var response = instance.OrderdetailsGet(orderId);
            //Assert.IsType<List<OrderDetailDto>>(response);
        }

        /// <summary>
        /// Test OrderdetailsPost
        /// </summary>
        [Fact]
        public void OrderdetailsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderdetailPostDto orderdetailPostDto = null;
            //instance.OrderdetailsPost(orderdetailPostDto);
        }

        /// <summary>
        /// Test OrdersGet
        /// </summary>
        [Fact]
        public void OrdersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int employeeId = null;
            //string customerId = null;
            //var response = instance.OrdersGet(employeeId, customerId);
            //Assert.IsType<List<OrderDto>>(response);
        }

        /// <summary>
        /// Test OrdersIdDelete
        /// </summary>
        [Fact]
        public void OrdersIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.OrdersIdDelete(id);
        }

        /// <summary>
        /// Test OrdersPost
        /// </summary>
        [Fact]
        public void OrdersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderPostDto orderPostDto = null;
            //instance.OrdersPost(orderPostDto);
        }

        /// <summary>
        /// Test ProductsGet
        /// </summary>
        [Fact]
        public void ProductsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ProductsGet();
            //Assert.IsType<List<ProductDto>>(response);
        }
    }
}
